### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by AaronDavidSchneider** [exorad/GCMtools#2]
1) Dialog system
SK: I think it would be a good idea to add a fixed console output system.
I usually use this:
 - [INFO] for everything that is just an information
 - [WARN] for our warnings
 - [STAT] for current status updates (for example progress of long loops)

Would you also like to add this?

RB: Sure, that sounds like a good idea to improve readability!
(While this discussion file was a good opportunity to test my git setup and push
back the answer, maybe we should Github's integrated 'Issue' tab for further
discussion?)

**Comment by Kiefersv** [comment]
The consol output was added with merg #14. I consider this Issue resolved for now but we might want to discuss it in the future. In my opinion we can close this issue now and bring it up in more detail once it arises again. @AaronDavidSchneider if you agree, please close it.
