### ISSUE TITLE
Read-in strategy: via cubedsphere or completely integrated?

### ISSUE THREAD

**Issue by robinbaeyens** [exorad/GCMtools#4]
I have now implemented a basic read-in function for the raw MITgcm data, which is completely based on @AaronDavidSchneider 's cubedsphere package. (Because the regridding is necessary anyway.)

Now the question arises: do we want to keep the GCMtools read-in function as a wrapper around the cubedsphere package? I am not sure if it makes much sense to have two separate packages, but maybe you guys have a different view?

Another aspect is the post-processing. Out of laziness, I just used the automatic post-processing in cubedsphere, but it might be useful and more flexible to implement this stuff into GCMtools instead. 

Let me know what you think!

**Comment by AaronDavidSchneider** [comment]
Fixed in PR #5
